version: "2"
services:
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - database:/var/lib/mysql
      - ./mysql/dumps/:/root/dumps
      - ./mysql/init-test-db.sql:/data/application/init.sql
  nest_e2e:
    container_name: nest_e2e
    depends_on:
      - mysql
    image: node:16.18
    ports:
      - "3010:3010"
    volumes:
      - ../:/home/node/app
    working_dir: /home/node/app/packages/api-core
    command:
      - /bin/sh
      - -c
      - |
        sort -u -t '=' -k 1,1 ../../.env.ci.test ../../.env.test > tmp
        cat tmp > ../../.env.test
        rm tmp
        npm run test:e2e
volumes:
  database:
