version: "2"
services:
  mysql:
    build: ./mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db-camap
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    networks:
      camap-net:
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./mysql/dumps/:/root/dumps
  nest-camap:
    depends_on:
      - mysql
    image: node:16.14
    container_name: nest-camap
    networks:
      camap-net:
    ports:
      - "127.0.0.1:3010:3010"
    expose:
      - 6007
    volumes:
      - ../:/home/node/app
    working_dir: /home/node/app/packages/api-core
    command: npm run start:prod
  neko-camap:
    build: ./neko
    container_name: neko-camap
    networks:
      camap-net:
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ../../camap-hx:/var/www/
    depends_on:
      - mysql
      - nest-camap
volumes:
  database:

networks:
  camap-net:
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.254
          ip_range: 192.168.3.0/24
