import { CamapError } from '../../common/errors/camap.error';

export enum DistributionsServiceFailReason {
  MULTI_DISTRIB_IS_ALREADY_VALIDATED = 'MULTI_DISTRIB_IS_ALREADY_VALIDATED',
  NOT_YET_DISTRIBUTED = 'NOT_YET_DISTRIBUTED',
  MULTI_DISTRIB_ALREADY_EXISTS_FOR_THIS_PLACE_AND_DATE = 'MULTI_DISTRIB_ALREADY_EXISTS_FOR_THIS_PLACE_AND_DATE',
  MULTI_DISTRIB_START_DATE_BEFORE_ORDER_END_DATE = 'MULTI_DISTRIB_START_DATE_BEFORE_ORDER_END_DATE',
  MULTI_DISTRIB_ORDER_START_DATE_AFTER_ORDER_END_DATE = 'MULTI_DISTRIB_ORDER_START_DATE_AFTER_ORDER_END_DATE',
  DISTRIBUTION_EXISTING_PAID_SUBSCRIPTIONS = 'DISTRIBUTION_EXISTING_PAID_SUBSCRIPTIONS',
  DISTRIBUTION_EXISTING_SUBSCRIPTIONS = 'DISTRIBUTION_EXISTING_SUBSCRIPTIONS',
  DISTRIBUTION_EXISTING_ORDERS = 'DISTRIBUTION_EXISTING_ORDERS',
  DISTRIBUTION_CATALOG_ALREADY_PARTICIPATING = 'DISTRIBUTION_CATALOG_ALREADY_PARTICIPATING',
  DISTRIBUTION_VENDOR_DISABLED = 'DISTRIBUTION_VENDOR_DISABLED',
  DISTRIBUTION_DATE_AFTER_CATALOG_END = 'DISTRIBUTION_DATE_AFTER_CATALOG_END',
  DISTRIBUTION_DATE_BEFORE_CATALOG_START = 'DISTRIBUTION_DATE_BEFORE_CATALOG_START',
  DISTRIBUTION_DATE_AFTER_ORDER_END_DATE = 'DISTRIBUTION_DATE_BEFORE_ORDER_END_DATE',
  DISTRIBUTION_DATE_BEFORE_ORDER_END_DATE = 'DISTRIBUTION_DATE_BEFORE_ORDER_END_DATE',
  DISTRIBUTION_ORDER_START_DATE_AFTER_ORDER_END_DATE = 'DISTRIBUTION_ORDER_START_DATE_AFTER_ORDER_END_DATE',
  DISTRIBUTION_CAMAP_PRO_CATALOG = 'DISTRIBUTION_CAMAP_PRO_CATALOG',
}

export class DistributionsServiceError extends CamapError<DistributionsServiceFailReason> {
  static NAME = 'DistributionsServiceError';
  name = DistributionsServiceError.NAME;

  constructor(
    public readonly reason: DistributionsServiceFailReason,
    public readonly props?: any,
  ) {
    super(reason);
  }
}
