name: Publish feature image to GHCR (camap-ts)

on:
  push:
    tags:
      - 'feature-*'     # ex: feature-producteur, feature-producteur-1
    branches:
      - 'feature/**'    # ex: feature/producteur

permissions:
  contents: read
  packages: write

jobs:
  verify-feature:
    name: Verify ref complies with feature rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Ensure ref is allowed (not master/staging; tags from feature/*)
        env:
          REF_NAME: ${{ github.ref_name }}
          REF_TYPE: ${{ github.ref_type }}   # 'branch' or 'tag'
        run: |
          set -euo pipefail

          echo "Ref name: ${REF_NAME}"
          echo "Ref type: ${REF_TYPE}"

          # Récupération des branches utiles pour les contrôles
          git fetch --prune origin \
            +refs/heads/master:refs/remotes/origin/master \
            +refs/heads/staging:refs/remotes/origin/staging \
            '+refs/heads/feature/*:refs/remotes/origin/feature/*'

          # Interdit si le commit est contenu dans master ou staging
          if git branch -r --contains HEAD | grep -Eq 'origin/(master|staging)'; then
            echo "❌ Le commit est contenu dans master ou staging (interdit pour ce workflow)." >&2
            exit 1
          fi

          if [ "${REF_TYPE}" = "tag" ]; then
            # Tag doit matcher feature-*
            case "${REF_NAME}" in
              feature-*) ;;
              *)
                echo "❌ Le tag '${REF_NAME}' ne commence pas par 'feature-'." >&2
                exit 1
                ;;
            esac

            # Le commit taggé doit être contenu dans au moins une branche feature/*
            if ! git branch -r --contains HEAD | grep -Eq 'origin/feature/'; then
              echo "❌ Ce tag feature-* n'est pas créé depuis une branche feature/*." >&2
              exit 1
            fi
            echo "✅ Tag feature-* valide et contenu dans une branche feature/*."

          elif [ "${REF_TYPE}" = "branch" ]; then
            # La branche doit être feature/*
            case "${REF_NAME}" in
              feature/*) echo "✅ Branche feature/* valide." ;;
              *)
                echo "❌ Seules les branches feature/* sont autorisées." >&2
                exit 1
                ;;
            esac
          else
            echo "❌ Type de ref inattendu: ${REF_TYPE}" >&2
            exit 1
          fi

  build-and-push:
    name: Build & push camap-ts
    needs: verify-feature
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/camap-app/camap-ts
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug workspace
        run: |
          pwd
          echo "---- root ----"
          ls -la
          echo "---- expected paths ----"
          ls -la packages || true
          ls -la public   || true
          ls -la scripts  || true
          ls -la package.json package-lock.json || true
          echo "---- .dockerignore ----"
          [ -f .dockerignore ] && sed -n '1,200p' .dockerignore || echo "(absent)"

      # ====== Cas 1 : build sur TAG feature-* ======
      - name: Prepare tag-based metadata
        id: tag_meta
        if: github.ref_type == 'tag'
        run: |
          set -euo pipefail
          ref="${GITHUB_REF_NAME}"                 # ex: feature-producteur-1
          short_sha="$(git rev-parse --short=8 HEAD)"
          sanitized="${ref// /-}"                  # sécurité: espaces -> '-'
          echo "tag=${sanitized}" >> "$GITHUB_OUTPUT"
          echo "tag_sha=${sanitized}-${short_sha}" >> "$GITHUB_OUTPUT"

      - name: Build & push (tag feature-*)
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./camap-ts.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.tag_meta.outputs.tag }}
            ${{ env.IMAGE_NAME }}:${{ steps.tag_meta.outputs.tag_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ====== Cas 2 : build sur BRANCHE feature/* ======
      - name: Prepare branch-based metadata
        id: branch_meta
        if: github.ref_type == 'branch'
        run: |
          set -euo pipefail
          b="${GITHUB_REF_NAME}"                    # ex: feature/producteur
          b_sanitized="${b//\//-}"                  # ex: feature-producteur
          short_sha="$(git rev-parse --short=8 HEAD)"
          echo "branch=${b_sanitized}"                  >> "$GITHUB_OUTPUT"
          echo "branch_sha=${b_sanitized}-${short_sha}" >> "$GITHUB_OUTPUT"

      - name: Build & push (feature/*)
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./camap-ts.Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.branch_meta.outputs.branch }}
            ${{ env.IMAGE_NAME }}:${{ steps.branch_meta.outputs.branch_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
